### ISSUE TITLE
Installation Instructions are confusing

### ISSUE THREAD

**Issue by BUMPRW** [dennypage/weewx-hubitat#1]
Your installation instructions seem confusing. 
Could you please clarify the instructions.  I know I have to deal with install.py and hubitat.py.  Do I place the weewx-hubitat-master.tar.gz in a specific location? I know hubitat.py has to be in the bin/user directory which I know exists within the tarball.  The zsh terminal on MAC OS 12.3.1 only allows me to double click wee-extension which faults because it can't find the file.  If you try to run wee-extension inside the terminal as you specify zsh: command not found: wee_extension even if you are in the same directory.  I could go on with what I have tried, but it seems I'm going in circles.

Please help and clarify.

**Comment by dennypage** [comment]
Apologies, I didn't notice the issue being opened. 

The wee_extension command is located in the binary directory of weewx. I.E. PATH_TO_WEEWX/bin/wee_extension.

I added a link to the wee_extension documentation in the WeeWX Utilities Guide.
